import { createHash } from "node:crypto";
import type { HarnessManifest } from "./harness-manifest";
import type { TierEntry } from "./harness-kernel";

/**
 * Compile targets -- the render/emit stage (Phase 0, 0.2b). A target is a pure
 * renderer over the resolved manifest, producing a content-addressed,
 * provenance-stamped artifact (docs/harness/03 Section 4 + 7). Deterministic:
 * no clock, no network, no randomness -- so the same resolved manifest always
 * yields the same artifact + hash. 0.2b ships the deploy-scope target only
 * (closes symptom S1); more targets (context bundle, packs, AGENTS.md, tier
 * table) land in later slices.
 */

export interface CompiledArtifact {
  /** Which target produced this (e.g. "deploy-scope"). */
  readonly target: string;
  /** Where it materializes, relative to the project anchor. */
  readonly path: string;
  readonly content: string;
  /** sha256 of content -- the content-address (A4). */
  readonly hash: string;
  /** Which resolved-manifest fields + kernel version this came from. No timestamp (determinism). */
  readonly provenance: { readonly kernel: string; readonly from: readonly string[] };
}

const DO_NOT_EDIT = "# GENERATED by the harness -- DO NOT EDIT. Recompile via `harness compile`.";

function sha256(s: string): string {
  return createHash("sha256").update(s).digest("hex");
}

/**
 * Deploy-scope target: the project perimeter -> the deploy ignore file. The
 * eradication mechanism for S1 (foreign monorepo weight leaking into a deploy):
 * the ignore file is generated from perimeter.exclude, never hand-authored, so a
 * deploy physically cannot reach outside the declared perimeter.
 */
export function emitDeployScope(resolved: HarnessManifest, kernelVersion: string): CompiledArtifact {
  const excludes = resolved.perimeter?.exclude ?? [];
  const lines = [
    DO_NOT_EDIT,
    `# Source: perimeter.exclude (${excludes.length} pattern(s)) + kernel ${kernelVersion}`,
    "",
    ...excludes,
  ];
  const content = lines.join("\n") + "\n";
  return {
    target: "deploy-scope",
    path: ".vercelignore",
    content,
    hash: sha256(content),
    provenance: { kernel: kernelVersion, from: ["perimeter.exclude"] },
  };
}

/**
 * AGENTS.md target: the portable operating-instructions artifact (docs/harness/
 * 20 -- the emit target every AGENTS.md-reading tool understands). Rendered from
 * the resolved manifest: identity, the route-by-judgment ladder, the gate
 * posture, and the perimeter. The context/charter inlining is the context-bundle
 * target (a follow-on that rewires the existing block compiler).
 */
export function emitAgentsMd(resolved: HarnessManifest, kernelVersion: string): CompiledArtifact {
  const id = resolved.identity;
  const tiers = resolved.routing?.tiers ?? [];
  const overrides = resolved.routing?.overrides ?? {};
  const gates = resolved.evaluation?.gates ?? {};
  const guardrails = resolved.safety?.guardrails ?? [];
  const lines: string[] = [
    `# ${id.name} -- operating instructions`,
    "",
    "<!-- GENERATED by the harness -- DO NOT EDIT. Change the manifest or the kernel, then recompile. -->",
    `<!-- kernel ${kernelVersion} -->`,
    "",
    `You are operating on **${id.name}** (${id.kind}; owners: ${id.owners.join(", ")}).`,
    "",
    "## Model routing (route by the judgment the task needs)",
    `- default tier: \`${resolved.routing?.default ?? "scoped"}\``,
    `- available tiers: ${tiers.map((t) => `\`${t}\``).join(", ") || "(inherited)"}`,
    ...Object.entries(overrides).map(([role, tier]) => `- ${role} runs on \`${tier}\``),
    "- gates, refuters, and the orchestrator run on a judgment tier; only mechanical labor routes down.",
    "",
    "## Gates",
    `- promotion gates: ${(gates.promote ?? []).join(", ") || "(none declared)"}`,
    `- tier-swap gates: ${(gates.tier_swap ?? []).join(", ") || "(none declared)"}`,
    `- guardrails: ${guardrails.join(", ") || "(kernel defaults)"}`,
    `- lethal-trifecta combinations are hard-blocked.`,
    "",
    "## Perimeter",
    resolved.perimeter?.deploy
      ? `- deploy scope: \`${resolved.perimeter.deploy.scope ?? ""}\` -> ${resolved.perimeter.deploy.surface ?? ""}`
      : "- no deploy surface.",
    `- excludes: ${(resolved.perimeter?.exclude ?? []).join(", ") || "(none)"}`,
  ];
  const content = lines.join("\n") + "\n";
  return {
    target: "agents-md",
    path: "AGENTS.md",
    content,
    hash: sha256(content),
    provenance: { kernel: kernelVersion, from: ["identity", "routing", "evaluation.gates", "safety", "perimeter"] },
  };
}

/**
 * Tier-table target: resolve the project's allowed tier aliases against the
 * kernel tier registry (docs/harness/11) into concrete (provider, model,
 * transport, role). A tier not in the registry is surfaced as unresolvable.
 */
export function emitTierTable(
  resolved: HarnessManifest,
  registry: Readonly<Record<string, TierEntry>>,
  kernelVersion: string,
): CompiledArtifact {
  const tiers = resolved.routing?.tiers ?? [];
  const resolvedTiers = tiers.filter((t) => registry[t]).map((t) => ({ alias: t, ...registry[t] }));
  const unresolvable = tiers.filter((t) => !registry[t]);
  const content =
    JSON.stringify({ _generated: "harness -- do not edit", kernel: kernelVersion, tiers: resolvedTiers, unresolvable }, null, 2) + "\n";
  return {
    target: "tier-table",
    path: ".harness/tiers.json",
    content,
    hash: sha256(content),
    provenance: { kernel: kernelVersion, from: ["routing.tiers", "kernel.tier-registry"] },
  };
}

/**
 * Tool-set target: the resolved MCP list + the allow/ask/deny/hidden decision
 * table (docs/harness/13), machine-readable for the runtime. hidden is kept
 * distinct from deny (invisible vs visible-but-blocked).
 */
export function emitToolSet(resolved: HarnessManifest, kernelVersion: string): CompiledArtifact {
  const p = resolved.tools?.permissions ?? {};
  const content =
    JSON.stringify(
      {
        _generated: "harness -- do not edit",
        kernel: kernelVersion,
        mcp: resolved.tools?.mcp ?? [],
        permissions: { allow: p.allow ?? [], ask: p.ask ?? [], deny: p.deny ?? [], hidden: p.hidden ?? [] },
      },
      null,
      2,
    ) + "\n";
  return {
    target: "tool-set",
    path: ".harness/tools.json",
    content,
    hash: sha256(content),
    provenance: { kernel: kernelVersion, from: ["tools.mcp", "tools.permissions"] },
  };
}

/**
 * Compile the resolved manifest to shadow artifacts (docs/harness/03 Section 7).
 * Emits each target whose declaring fields are present. The result is written to
 * shadow by the caller; the adopter (0.3) is the only thing that materializes
 * shadow -> live. More targets (context bundle, packs, eval config) are
 * follow-ons.
 */
export function compileTargets(
  resolved: HarnessManifest,
  kernelVersion: string,
  tierRegistry: Readonly<Record<string, TierEntry>>,
): CompiledArtifact[] {
  const out: CompiledArtifact[] = [];
  out.push(emitAgentsMd(resolved, kernelVersion));
  if (resolved.routing?.tiers?.length) out.push(emitTierTable(resolved, tierRegistry, kernelVersion));
  if (resolved.tools) out.push(emitToolSet(resolved, kernelVersion));
  if (resolved.perimeter?.deploy) out.push(emitDeployScope(resolved, kernelVersion));
  return out;
}
