import { createHash } from "node:crypto";
import type { HarnessManifest } from "./harness-manifest";

/**
 * Compile targets -- the render/emit stage (Phase 0, 0.2b). A target is a pure
 * renderer over the resolved manifest, producing a content-addressed,
 * provenance-stamped artifact (docs/harness/03 Section 4 + 7). Deterministic:
 * no clock, no network, no randomness -- so the same resolved manifest always
 * yields the same artifact + hash. 0.2b ships the deploy-scope target only
 * (closes symptom S1); more targets (context bundle, packs, AGENTS.md, tier
 * table) land in later slices.
 */

export interface CompiledArtifact {
  /** Which target produced this (e.g. "deploy-scope"). */
  readonly target: string;
  /** Where it materializes, relative to the project anchor. */
  readonly path: string;
  readonly content: string;
  /** sha256 of content -- the content-address (A4). */
  readonly hash: string;
  /** Which resolved-manifest fields + kernel version this came from. No timestamp (determinism). */
  readonly provenance: { readonly kernel: string; readonly from: readonly string[] };
}

const DO_NOT_EDIT = "# GENERATED by the harness -- DO NOT EDIT. Recompile via `harness compile`.";

function sha256(s: string): string {
  return createHash("sha256").update(s).digest("hex");
}

/**
 * Deploy-scope target: the project perimeter -> the deploy ignore file. The
 * eradication mechanism for S1 (foreign monorepo weight leaking into a deploy):
 * the ignore file is generated from perimeter.exclude, never hand-authored, so a
 * deploy physically cannot reach outside the declared perimeter.
 */
export function emitDeployScope(resolved: HarnessManifest, kernelVersion: string): CompiledArtifact {
  const excludes = resolved.perimeter?.exclude ?? [];
  const lines = [
    DO_NOT_EDIT,
    `# Source: perimeter.exclude (${excludes.length} pattern(s)) + kernel ${kernelVersion}`,
    "",
    ...excludes,
  ];
  const content = lines.join("\n") + "\n";
  return {
    target: "deploy-scope",
    path: ".vercelignore",
    content,
    hash: sha256(content),
    provenance: { kernel: kernelVersion, from: ["perimeter.exclude"] },
  };
}

/**
 * Compile the resolved manifest to shadow artifacts. 0.2b: emits the
 * deploy-scope artifact when the project declares a deploy surface. The result
 * is written to the shadow tree by the caller; the adopter (0.3) is the only
 * thing that materializes shadow -> live.
 */
export function compileTargets(resolved: HarnessManifest, kernelVersion: string): CompiledArtifact[] {
  const out: CompiledArtifact[] = [];
  if (resolved.perimeter?.deploy) out.push(emitDeployScope(resolved, kernelVersion));
  return out;
}
